CREATE TABLE ACCOUNT (
    ACCOUNT_ID uuid PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(20) NOT NULL CHECK (TYPE IN ('FREE', 'PAID'))
);

CREATE TABLE PAID_ACCOUNT (
    ACCOUNT_ID uuid PRIMARY KEY,
    SUBSCRIPTION_TYPE VARCHAR(50) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    RENEWAL_DATE TIMESTAMP NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE FREE_ACCOUNT (
    ACCOUNT_ID uuid PRIMARY KEY,
    STORAGE_LIMIT_GB INT NOT NULL DEFAULT 2,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE ERASURE_PROFILE(
    ERASURE_ID VARCHAR(50) PRIMARY KEY NOT NULL CHECK (ERASURE_ID IN ('LOW', 'MEDIUM', 'HIGH')) DEFAULT 'MEDIUM',
    ACCOUNT_ID uuid NOT NULL,
    k INT NOT NULL,
    m INT NOT NULL,
    bytes INT NOT NULL,
    NOTES TEXT,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) 
);

CREATE TABLE FILE_OBJECTS (
    FILE_ID uuid PRIMARY KEY,
    ACCOUNT_ID uuid NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_SIZE BIGINT NOT NULL,
    UPLOADED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOGICAL_PATH TEXT NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

CREATE TABLE FILE_VERSIONS (
    VERSION_ID uuid PRIMARY KEY,
    FILE_ID uuid NOT NULL,
    ERASURE_ID VARCHAR(50) NOT NULL,
    BYTES BIGINT NOT NULL,
    CONTENT_HASH VARCHAR(64) NOT NULL,
    UPLOADED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FILE_ID) REFERENCES FILE_OBJECTS(FILE_ID),
    FOREIGN KEY (ERASURE_ID) REFERENCES ERASURE_PROFILE(ERASURE_ID)
);

CREATE TABLE FILE_SEGMENTS (
    SEGMENT_ID uuid PRIMARY KEY,
    VERSION_ID uuid NOT NULL,
    ERASURE_ID VARCHAR(50) NOT NULL,
    NUM_SEGMENT INT NOT NULL,
    BYTES BIGINT NOT NULL,
    CONTENT_HASH VARCHAR(64) NOT NULL,
    STORED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VERSION_ID) REFERENCES FILE_VERSIONS(VERSION_ID),
    FOREIGN KEY (ERASURE_ID) REFERENCES ERASURE_PROFILE(ERASURE_ID)
);

CREATE TABLE FILE_FRAGMENTS (
    FRAGMENT_ID uuid PRIMARY KEY,
    SEGMENT_ID uuid NOT NULL,
    NUM_FRAGMENT INT NOT NULL,
    BYTES BIGINT NOT NULL,
    CONTENT_HASH VARCHAR(64) NOT NULL,
    STORED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SEGMENT_ID) REFERENCES FILE_SEGMENTS(SEGMENT_ID)
);

CREATE TABLE NODE_STORAGE (
    NODE_ID uuid PRIMARY KEY,
    API_ENDPOINT VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL CHECK (ROLE IN ('STORAGE', 'MASTER', 'FOLLOWER'))
    HOSTNAME VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    UPTIMED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HEARTBEAT_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LATENCY_MS INT NOT NULL DEFAULT 0
);

CREATE TABLE NODE_HEARTBEAT(
    NODE_ID uuid PRIMARY KEY,
    UPTIMED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HEARTBEAT_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LATENCY_MS INT NOT NULL DEFAULT 0,
    FOREIGN KEY (NODE_ID) REFERENCES NODE_STORAGE(NODE_ID)
);

CREATE TABLE NODE_CAPACITY (
    NODE_ID uuid PRIMARY KEY,
    TOTAL_BYTES BIGINT NOT NULL,
    USED_BYTES BIGINT NOT NULL,
    AVAILABLE_BYTES BIGINT NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (NODE_ID) REFERENCES NODE_STORAGE(NODE_ID)
);

CREATE TABLE FRAGMENT_LOCATION (
    FRAGMENT_ID BIGINT PRIMARY KEY,
    NODE_ID uuid NOT NULL,
    FRAGMENT_ADDRESS VARCHAR(255) NOT NULL,
    STORED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    BYTES BIGINT NOT NULL,
    LAST_CHECKED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FRAGMENT_ID) REFERENCES FILE_FRAGMENTS(FRAGMENT_ID),
    FOREIGN KEY (NODE_ID) REFERENCES NODE_STORAGE(NODE_ID)
);

CREATE TABLE FILE_KEYS (
    KEY_ID uuid PRIMARY KEY,
    VERSION_ID uuid NOT NULL,
    ENCRYPTION_KEY VARCHAR(512) NOT NULL,
    KEY_CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (VERSION_ID) REFERENCES FILE_VERSIONS(VERSION_ID)
);

CREATE TABLE KEY_SHARE(
    KEY_ID uuid PRIMARY KEY,
    KEY_SHARE_ID BIGINT NOT NULL,
    NODE_ID uuid NOT NULL,
    SHARE_BYTES BIGINT NOT NULL,
    SHARE_ADDRESS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (KEY_ID) REFERENCES FILE_KEYS(KEY_ID),
    FOREIGN KEY (NODE_ID) REFERENCES NODE_STORAGE(NODE_ID)
);

CREATE TABLE REPAIR_JOBS (
    JOB_ID uuid PRIMARY KEY,
    VERSION_ID uuid NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STARTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    FOREIGN KEY (VERSION_ID) REFERENCES FILE_VERSIONS(VERSION_ID)
);

CREATE TABLE WORKERS(
    WORKER_ID uuid PRIMARY KEY,
    JOB_ID uuid NOT NULL,
    FRAGMENT_ID BIGINT NOT NULL,
    NODE_ID uuid NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED')),
    ASSIGNED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    FOREIGN KEY (JOB_ID) REFERENCES REPAIR_JOBS(JOB_ID),
    FOREIGN KEY (FRAGMENT_ID) REFERENCES FILE_FRAGMENTS(FRAGMENT_ID),
    FOREIGN KEY (NODE_ID) REFERENCES NODE_STORAGE(NODE_ID)
);